/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../farsava_model/Error';
import LanguageModelResult from '../farsava_model/LanguageModelResult';
import LanguageModelTrainRequestBody from '../farsava_model/LanguageModelTrainRequestBody';

/**
* LanguageModel service.
* @module farsava_js_sdk/farsava_api/LanguageModelApi
* @version 1.0.5
*/
export default class LanguageModelApi {

    /**
    * Constructs a new LanguageModelApi. 
    * @alias module:farsava_js_sdk/farsava_api/LanguageModelApi
    * @class
    * @param {module:farsava_js_sdk/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:farsava_js_sdk/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getLanguageModelById operation.
     * @callback module:farsava_js_sdk/farsava_api/LanguageModelApi~getLanguageModelByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:farsava_js_sdk/farsava_model/LanguageModelResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GET /speech/languagemodels/{languageModelId}
     * Retrieving the status of a language model with specified languageModelId. A language model is ready to use when its status is *trained*. *** 
     * @param {String} languageModelId Id of the language model.
     * @param {module:farsava_js_sdk/farsava_api/LanguageModelApi~getLanguageModelByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:farsava_js_sdk/farsava_model/LanguageModelResult}
     */
    getLanguageModelById(languageModelId, callback) {
      let postBody = null;
      // verify the required parameter 'languageModelId' is set
      if (languageModelId === undefined || languageModelId === null) {
        throw new Error("Missing the required parameter 'languageModelId' when calling getLanguageModelById");
      }

      let pathParams = {
        'languageModelId': languageModelId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LanguageModelResult;
      return this.apiClient.callApi(
        '/speech/languagemodels/{languageModelId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLanguageModelList operation.
     * @callback module:farsava_js_sdk/farsava_api/LanguageModelApi~getLanguageModelListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:farsava_js_sdk/farsava_model/LanguageModelResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GET /speech/languagemodels
     * Returns list of user available language models. Each user can access *general* language models plus their own *custom* trained language models. *** 
     * @param {module:farsava_js_sdk/farsava_api/LanguageModelApi~getLanguageModelListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:farsava_js_sdk/farsava_model/LanguageModelResult>}
     */
    getLanguageModelList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LanguageModelResult];
      return this.apiClient.callApi(
        '/speech/languagemodels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the trainLanguageModel operation.
     * @callback module:farsava_js_sdk/farsava_api/LanguageModelApi~trainLanguageModelCallback
     * @param {String} error Error message, if any.
     * @param {module:farsava_js_sdk/farsava_model/LanguageModelResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * POST /speech/languagemodels
     * Train a custom language model using pharases provided by user. Returning a languageModelId for accessing the language model later and using this custom language model to transcribe audios. Using custom language models will boost accuracy for specific keywords/phrases and can be used for a domain-specific speech recognition. *** 
     * @param {module:farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody} languageModelTrainRequestBody A json object including a name and a corpora. Corpora is a array of text data to train a custom model. This text data can be keywords/phrases. All values in the array must be a string. Name is an arbitary string you set for the custom language model name.
     * @param {module:farsava_js_sdk/farsava_api/LanguageModelApi~trainLanguageModelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:farsava_js_sdk/farsava_model/LanguageModelResult}
     */
    trainLanguageModel(languageModelTrainRequestBody, callback) {
      let postBody = languageModelTrainRequestBody;
      // verify the required parameter 'languageModelTrainRequestBody' is set
      if (languageModelTrainRequestBody === undefined || languageModelTrainRequestBody === null) {
        throw new Error("Missing the required parameter 'languageModelTrainRequestBody' when calling trainLanguageModel");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LanguageModelResult;
      return this.apiClient.callApi(
        '/speech/languagemodels', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
