/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../farsava_model/Error';
import HealthCheckResponseBody from '../farsava_model/HealthCheckResponseBody';
import TTSRequestBody from '../farsava_model/TTSRequestBody';
import TTSResponseBody from '../farsava_model/TTSResponseBody';
import VoiceSelectionParams from '../farsava_model/VoiceSelectionParams';

/**
* Voice service.
* @module farsava_js_sdk/farsava_api/VoiceApi
* @version 1.0.5
*/
export default class VoiceApi {

    /**
    * Constructs a new VoiceApi. 
    * @alias module:farsava_js_sdk/farsava_api/VoiceApi
    * @class
    * @param {module:farsava_js_sdk/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:farsava_js_sdk/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getVoicesList operation.
     * @callback module:farsava_js_sdk/farsava_api/VoiceApi~getVoicesListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:farsava_js_sdk/farsava_model/VoiceSelectionParams>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GET /voice/speakers
     * This endpoint retrieves the list of available speakers for speech synthesization. Each speaker has a unique *voiceId* which can be used to synthesize speech. The result aslo includes each speaker langauge, gender and name. *** 
     * @param {module:farsava_js_sdk/farsava_api/VoiceApi~getVoicesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:farsava_js_sdk/farsava_model/VoiceSelectionParams>}
     */
    getVoicesList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [VoiceSelectionParams];
      return this.apiClient.callApi(
        '/voice/speakers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the synthesize operation.
     * @callback module:farsava_js_sdk/farsava_api/VoiceApi~synthesizeCallback
     * @param {String} error Error message, if any.
     * @param {module:farsava_js_sdk/farsava_model/TTSResponseBody} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * POST /voice/tts
     * ## Synthesizes speech synchronously  *** Receives text and data configs and synthesize speech in different voices and format using state-of-the-art deep neural networks. This service synthesizes speech synchronously and the results will be available after all text input has been processed.  *** Using *config* object you can can specify audio configs such as *audioEncoding* and *sampleRateHertz*. We will support different languages so you can choose the *languageCode*. using *voiceSelectionParams* you can choose between the supported voices with specifying voiceId. Voices differ in gender, tone and style.  
     * @param {module:farsava_js_sdk/farsava_model/TTSRequestBody} tTSRequestBody Receives a json including input text, voice parameteres and audio config. 
     * @param {module:farsava_js_sdk/farsava_api/VoiceApi~synthesizeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:farsava_js_sdk/farsava_model/TTSResponseBody}
     */
    synthesize(tTSRequestBody, callback) {
      let postBody = tTSRequestBody;
      // verify the required parameter 'tTSRequestBody' is set
      if (tTSRequestBody === undefined || tTSRequestBody === null) {
        throw new Error("Missing the required parameter 'tTSRequestBody' when calling synthesize");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TTSResponseBody;
      return this.apiClient.callApi(
        '/voice/tts', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the voiceHealthCheck operation.
     * @callback module:farsava_js_sdk/farsava_api/VoiceApi~voiceHealthCheckCallback
     * @param {String} error Error message, if any.
     * @param {module:farsava_js_sdk/farsava_model/HealthCheckResponseBody} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GET /voice/healthcheck
     * ## voice health check endpoint. *** This endpoint will return a simple json including **service status** and **API version**. 
     * @param {module:farsava_js_sdk/farsava_api/VoiceApi~voiceHealthCheckCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:farsava_js_sdk/farsava_model/HealthCheckResponseBody}
     */
    voiceHealthCheck(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HealthCheckResponseBody;
      return this.apiClient.callApi(
        '/voice/healthcheck', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
