/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ASRStatus.
* @enum {}
* @readonly
*/
export default class ASRStatus {
    
        /**
         * value: "queued"
         * @const
         */
        "queued" = "queued";

    
        /**
         * value: "processing"
         * @const
         */
        "processing" = "processing";

    
        /**
         * value: "done"
         * @const
         */
        "done" = "done";

    
        /**
         * value: "partial"
         * @const
         */
        "partial" = "partial";

    

    /**
    * Returns a <code>ASRStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:farsava_js_sdk/farsava_model/ASRStatus} The enum <code>ASRStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

