/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LanguageCode.
* @enum {}
* @readonly
*/
export default class LanguageCode {
    
        /**
         * value: "fa"
         * @const
         */
        "fa" = "fa";

    
        /**
         * value: "en"
         * @const
         */
        "en" = "en";

    

    /**
    * Returns a <code>LanguageCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:farsava_js_sdk/farsava_model/LanguageCode} The enum <code>LanguageCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

