/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LanguageModelTrainRequestBody model module.
 * @module farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody
 * @version 1.0.5
 */
class LanguageModelTrainRequestBody {
    /**
     * Constructs a new <code>LanguageModelTrainRequestBody</code>.
     * @alias module:farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody
     * @param corpora {Array.<String>} An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.      
     */
    constructor(corpora) { 
        
        LanguageModelTrainRequestBody.initialize(this, corpora);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, corpora) { 
        obj['corpora'] = corpora;
    }

    /**
     * Constructs a <code>LanguageModelTrainRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody} The populated <code>LanguageModelTrainRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LanguageModelTrainRequestBody();

            if (data.hasOwnProperty('corpora')) {
                obj['corpora'] = ApiClient.convertToType(data['corpora'], ['String']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

/**
     * Returns An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.      
     * @return {Array.<String>}
     */
    getCorpora() {
        return this.corpora;
    }

    /**
     * Sets An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.      
     * @param {Array.<String>} corpora An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.      
     */
    setCorpora(corpora) {
        this['corpora'] = corpora;
    }
/**
     * Returns The name of the custom language model being created. 
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * Sets The name of the custom language model being created. 
     * @param {String} name The name of the custom language model being created. 
     */
    setName(name) {
        this['name'] = name;
    }

}

/**
 * An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.      
 * @member {Array.<String>} corpora
 */
LanguageModelTrainRequestBody.prototype['corpora'] = undefined;

/**
 * The name of the custom language model being created. 
 * @member {String} name
 */
LanguageModelTrainRequestBody.prototype['name'] = undefined;






export default LanguageModelTrainRequestBody;

