/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecognitionAudioData model module.
 * @module farsava_js_sdk/farsava_model/RecognitionAudioData
 * @version 1.0.5
 */
class RecognitionAudioData {
    /**
     * Constructs a new <code>RecognitionAudioData</code>.
     * Contains audio data in the encoding specified in the RecognitionConfig.    A base64-encoded string.   *For asr endpoint only binary data is accepted.*      Property | Description   ------------ | -------------   data | The audio data bytes encoded as specified in RecognitionConfig. A base64-encoded string. 
     * @alias module:farsava_js_sdk/farsava_model/RecognitionAudioData
     * @param data {Blob} The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string. 
     */
    constructor(data) { 
        
        RecognitionAudioData.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>RecognitionAudioData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/RecognitionAudioData} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/RecognitionAudioData} The populated <code>RecognitionAudioData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecognitionAudioData();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
            }
        }
        return obj;
    }

/**
     * Returns The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string. 
     * @return {Blob}
     */
    getData() {
        return this.data;
    }

    /**
     * Sets The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string. 
     * @param {Blob} data The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string. 
     */
    setData(data) {
        this['data'] = data;
    }

}

/**
 * The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string. 
 * @member {Blob} data
 */
RecognitionAudioData.prototype['data'] = undefined;






export default RecognitionAudioData;

