/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecognitionAudioURI model module.
 * @module farsava_js_sdk/farsava_model/RecognitionAudioURI
 * @version 1.0.5
 */
class RecognitionAudioURI {
    /**
     * Constructs a new <code>RecognitionAudioURI</code>.
     * Contains audio source URI with the encoding specified in the RecognitionConfig.    *For asrlongrunning endpoint only uri is accepted.*      Property | Description   ------------ | -------------   uri | URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
     * @alias module:farsava_js_sdk/farsava_model/RecognitionAudioURI
     * @param uri {String} URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
     */
    constructor(uri) { 
        
        RecognitionAudioURI.initialize(this, uri);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uri) { 
        obj['uri'] = uri;
    }

    /**
     * Constructs a <code>RecognitionAudioURI</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/RecognitionAudioURI} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/RecognitionAudioURI} The populated <code>RecognitionAudioURI</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecognitionAudioURI();

            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }

/**
     * Returns URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
     * @return {String}
     */
    getUri() {
        return this.uri;
    }

    /**
     * Sets URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
     * @param {String} uri URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
     */
    setUri(uri) {
        this['uri'] = uri;
    }

}

/**
 * URI that points to a file that contains audio data bytes as specified in RecognitionConfig. The file must not be compressed (for example, gzip). 
 * @member {String} uri
 */
RecognitionAudioURI.prototype['uri'] = undefined;






export default RecognitionAudioURI;

