/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SpeechRecognitionModel.
* @enum {}
* @readonly
*/
export default class SpeechRecognitionModel {
    
        /**
         * value: "default"
         * @const
         */
        "default" = "default";

    
        /**
         * value: "video"
         * @const
         */
        "video" = "video";

    
        /**
         * value: "command_and_search"
         * @const
         */
        "command_and_search" = "command_and_search";

    
        /**
         * value: "phone_call"
         * @const
         */
        "phone_call" = "phone_call";

    

    /**
    * Returns a <code>SpeechRecognitionModel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:farsava_js_sdk/farsava_model/SpeechRecognitionModel} The enum <code>SpeechRecognitionModel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

