/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WordInfo from './WordInfo';

/**
 * The SpeechRecognitionResult model module.
 * @module farsava_js_sdk/farsava_model/SpeechRecognitionResult
 * @version 1.0.5
 */
class SpeechRecognitionResult {
    /**
     * Constructs a new <code>SpeechRecognitionResult</code>.
     * @alias module:farsava_js_sdk/farsava_model/SpeechRecognitionResult
     */
    constructor() { 
        
        SpeechRecognitionResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SpeechRecognitionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/SpeechRecognitionResult} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/SpeechRecognitionResult} The populated <code>SpeechRecognitionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpeechRecognitionResult();

            if (data.hasOwnProperty('transcript')) {
                obj['transcript'] = ApiClient.convertToType(data['transcript'], 'String');
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('words')) {
                obj['words'] = ApiClient.convertToType(data['words'], [WordInfo]);
            }
        }
        return obj;
    }

/**
     * Returns A UTF8-Encoded string. Transcript text representing the words that the user spoke. 
     * @return {String}
     */
    getTranscript() {
        return this.transcript;
    }

    /**
     * Sets A UTF8-Encoded string. Transcript text representing the words that the user spoke. 
     * @param {String} transcript A UTF8-Encoded string. Transcript text representing the words that the user spoke. 
     */
    setTranscript(transcript) {
        this['transcript'] = transcript;
    }
/**
     * Returns The confidence of ASR engine for generated output. The confidence estimate between 0.0 and 1.0. A higher number indicates an estimated greater likelihood that the recognized words are correct. It is the total confidence of recognition in transcript level and each word confidence in word info object. This field is not guaranteed to be accurate and users should not rely on it to be always provided. The default of 0.0 is a sentinel value indicating confidence was not set. 
     * minimum: 0
     * maximum: 1
     * @return {Number}
     */
    getConfidence() {
        return this.confidence;
    }

    /**
     * Sets The confidence of ASR engine for generated output. The confidence estimate between 0.0 and 1.0. A higher number indicates an estimated greater likelihood that the recognized words are correct. It is the total confidence of recognition in transcript level and each word confidence in word info object. This field is not guaranteed to be accurate and users should not rely on it to be always provided. The default of 0.0 is a sentinel value indicating confidence was not set. 
     * @param {Number} confidence The confidence of ASR engine for generated output. The confidence estimate between 0.0 and 1.0. A higher number indicates an estimated greater likelihood that the recognized words are correct. It is the total confidence of recognition in transcript level and each word confidence in word info object. This field is not guaranteed to be accurate and users should not rely on it to be always provided. The default of 0.0 is a sentinel value indicating confidence was not set. 
     */
    setConfidence(confidence) {
        this['confidence'] = confidence;
    }
/**
     * @return {Array.<module:farsava_js_sdk/farsava_model/WordInfo>}
     */
    getWords() {
        return this.words;
    }

    /**
     * @param {Array.<module:farsava_js_sdk/farsava_model/WordInfo>} words
     */
    setWords(words) {
        this['words'] = words;
    }

}

/**
 * A UTF8-Encoded string. Transcript text representing the words that the user spoke. 
 * @member {String} transcript
 */
SpeechRecognitionResult.prototype['transcript'] = undefined;

/**
 * The confidence of ASR engine for generated output. The confidence estimate between 0.0 and 1.0. A higher number indicates an estimated greater likelihood that the recognized words are correct. It is the total confidence of recognition in transcript level and each word confidence in word info object. This field is not guaranteed to be accurate and users should not rely on it to be always provided. The default of 0.0 is a sentinel value indicating confidence was not set. 
 * @member {Number} confidence
 */
SpeechRecognitionResult.prototype['confidence'] = undefined;

/**
 * @member {Array.<module:farsava_js_sdk/farsava_model/WordInfo>} words
 */
SpeechRecognitionResult.prototype['words'] = undefined;






export default SpeechRecognitionResult;

