/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AudioEncoding from './AudioEncoding';

/**
 * The TTSAudioConfig model module.
 * @module farsava_js_sdk/farsava_model/TTSAudioConfig
 * @version 1.0.5
 */
class TTSAudioConfig {
    /**
     * Constructs a new <code>TTSAudioConfig</code>.
     * The configuration of the synthesized audio.
     * @alias module:farsava_js_sdk/farsava_model/TTSAudioConfig
     * @param audioEncoding {module:farsava_js_sdk/farsava_model/AudioEncoding} 
     * @param sampleRateHertz {Number} Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen. 
     */
    constructor(audioEncoding, sampleRateHertz) { 
        
        TTSAudioConfig.initialize(this, audioEncoding, sampleRateHertz);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, audioEncoding, sampleRateHertz) { 
        obj['audioEncoding'] = audioEncoding;
        obj['sampleRateHertz'] = sampleRateHertz;
    }

    /**
     * Constructs a <code>TTSAudioConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/TTSAudioConfig} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/TTSAudioConfig} The populated <code>TTSAudioConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TTSAudioConfig();

            if (data.hasOwnProperty('audioEncoding')) {
                obj['audioEncoding'] = AudioEncoding.constructFromObject(data['audioEncoding']);
            }
            if (data.hasOwnProperty('sampleRateHertz')) {
                obj['sampleRateHertz'] = ApiClient.convertToType(data['sampleRateHertz'], 'Number');
            }
            if (data.hasOwnProperty('speakingRate')) {
                obj['speakingRate'] = ApiClient.convertToType(data['speakingRate'], 'Number');
            }
            if (data.hasOwnProperty('pitch')) {
                obj['pitch'] = ApiClient.convertToType(data['pitch'], 'Number');
            }
            if (data.hasOwnProperty('volumeGainDb')) {
                obj['volumeGainDb'] = ApiClient.convertToType(data['volumeGainDb'], 'Number');
            }
        }
        return obj;
    }

/**
     * @return {module:farsava_js_sdk/farsava_model/AudioEncoding}
     */
    getAudioEncoding() {
        return this.audioEncoding;
    }

    /**
     * @param {module:farsava_js_sdk/farsava_model/AudioEncoding} audioEncoding
     */
    setAudioEncoding(audioEncoding) {
        this['audioEncoding'] = audioEncoding;
    }
/**
     * Returns Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen. 
     * @return {Number}
     */
    getSampleRateHertz() {
        return this.sampleRateHertz;
    }

    /**
     * Sets Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen. 
     * @param {Number} sampleRateHertz Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen. 
     */
    setSampleRateHertz(sampleRateHertz) {
        this['sampleRateHertz'] = sampleRateHertz;
    }
/**
     * Returns Optional speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error. 
     * minimum: 0.25
     * maximum: 4
     * @return {Number}
     */
    getSpeakingRate() {
        return this.speakingRate;
    }

    /**
     * Sets Optional speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error. 
     * @param {Number} speakingRate Optional speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error. 
     */
    setSpeakingRate(speakingRate) {
        this['speakingRate'] = speakingRate;
    }
/**
     * Returns Optional speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch. 
     * minimum: -20.0
     * maximum: 20.0
     * @return {Number}
     */
    getPitch() {
        return this.pitch;
    }

    /**
     * Sets Optional speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch. 
     * @param {Number} pitch Optional speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch. 
     */
    setPitch(pitch) {
        this['pitch'] = pitch;
    }
/**
     * Returns Optional volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB) will play at approximately half the amplitude of the normal native signal amplitude. A value of +6.0 (dB) will play at approximately twice the amplitude of the normal native signal amplitude. Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that. 
     * minimum: -96.0
     * maximum: 16.0
     * @return {Number}
     */
    getVolumeGainDb() {
        return this.volumeGainDb;
    }

    /**
     * Sets Optional volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB) will play at approximately half the amplitude of the normal native signal amplitude. A value of +6.0 (dB) will play at approximately twice the amplitude of the normal native signal amplitude. Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that. 
     * @param {Number} volumeGainDb Optional volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB) will play at approximately half the amplitude of the normal native signal amplitude. A value of +6.0 (dB) will play at approximately twice the amplitude of the normal native signal amplitude. Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that. 
     */
    setVolumeGainDb(volumeGainDb) {
        this['volumeGainDb'] = volumeGainDb;
    }

}

/**
 * @member {module:farsava_js_sdk/farsava_model/AudioEncoding} audioEncoding
 */
TTSAudioConfig.prototype['audioEncoding'] = undefined;

/**
 * Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen. 
 * @member {Number} sampleRateHertz
 * @default 16000
 */
TTSAudioConfig.prototype['sampleRateHertz'] = 16000;

/**
 * Optional speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error. 
 * @member {Number} speakingRate
 */
TTSAudioConfig.prototype['speakingRate'] = undefined;

/**
 * Optional speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch. 
 * @member {Number} pitch
 */
TTSAudioConfig.prototype['pitch'] = undefined;

/**
 * Optional volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB) will play at approximately half the amplitude of the normal native signal amplitude. A value of +6.0 (dB) will play at approximately twice the amplitude of the normal native signal amplitude. Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that. 
 * @member {Number} volumeGainDb
 */
TTSAudioConfig.prototype['volumeGainDb'] = undefined;






export default TTSAudioConfig;

