/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TTSResponseBody model module.
 * @module farsava_js_sdk/farsava_model/TTSResponseBody
 * @version 1.0.5
 */
class TTSResponseBody {
    /**
     * Constructs a new <code>TTSResponseBody</code>.
     * @alias module:farsava_js_sdk/farsava_model/TTSResponseBody
     */
    constructor() { 
        
        TTSResponseBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TTSResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/TTSResponseBody} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/TTSResponseBody} The populated <code>TTSResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TTSResponseBody();

            if (data.hasOwnProperty('audioContent')) {
                obj['audioContent'] = ApiClient.convertToType(data['audioContent'], 'Blob');
            }
        }
        return obj;
    }

/**
     * Returns The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string. 
     * @return {Blob}
     */
    getAudioContent() {
        return this.audioContent;
    }

    /**
     * Sets The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string. 
     * @param {Blob} audioContent The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string. 
     */
    setAudioContent(audioContent) {
        this['audioContent'] = audioContent;
    }

}

/**
 * The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string. 
 * @member {Blob} audioContent
 */
TTSResponseBody.prototype['audioContent'] = undefined;






export default TTSResponseBody;

