/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SynthesisInput from './SynthesisInput';
import TTSAudioConfig from './TTSAudioConfig';
import VoiceSelectionParams from './VoiceSelectionParams';

/**
 * The TTSRequestBody model module.
 * @module farsava_js_sdk/farsava_model/TTSRequestBody
 * @version 1.0.5
 */
class TTSRequestBody {
    /**
     * Constructs a new <code>TTSRequestBody</code>.
     * @alias module:farsava_js_sdk/farsava_model/TTSRequestBody
     * @param synthesisInput {module:farsava_js_sdk/farsava_model/SynthesisInput} 
     * @param voiceConfig {module:farsava_js_sdk/farsava_model/VoiceSelectionParams} 
     * @param audioConfig {module:farsava_js_sdk/farsava_model/TTSAudioConfig} 
     */
    constructor(synthesisInput, voiceConfig, audioConfig) { 
        
        TTSRequestBody.initialize(this, synthesisInput, voiceConfig, audioConfig);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, synthesisInput, voiceConfig, audioConfig) { 
        obj['synthesisInput'] = synthesisInput;
        obj['voiceConfig'] = voiceConfig;
        obj['audioConfig'] = audioConfig;
    }

    /**
     * Constructs a <code>TTSRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:farsava_js_sdk/farsava_model/TTSRequestBody} obj Optional instance to populate.
     * @return {module:farsava_js_sdk/farsava_model/TTSRequestBody} The populated <code>TTSRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TTSRequestBody();

            if (data.hasOwnProperty('synthesisInput')) {
                obj['synthesisInput'] = SynthesisInput.constructFromObject(data['synthesisInput']);
            }
            if (data.hasOwnProperty('voiceConfig')) {
                obj['voiceConfig'] = VoiceSelectionParams.constructFromObject(data['voiceConfig']);
            }
            if (data.hasOwnProperty('audioConfig')) {
                obj['audioConfig'] = TTSAudioConfig.constructFromObject(data['audioConfig']);
            }
        }
        return obj;
    }

/**
     * @return {module:farsava_js_sdk/farsava_model/SynthesisInput}
     */
    getSynthesisInput() {
        return this.synthesisInput;
    }

    /**
     * @param {module:farsava_js_sdk/farsava_model/SynthesisInput} synthesisInput
     */
    setSynthesisInput(synthesisInput) {
        this['synthesisInput'] = synthesisInput;
    }
/**
     * @return {module:farsava_js_sdk/farsava_model/VoiceSelectionParams}
     */
    getVoiceConfig() {
        return this.voiceConfig;
    }

    /**
     * @param {module:farsava_js_sdk/farsava_model/VoiceSelectionParams} voiceConfig
     */
    setVoiceConfig(voiceConfig) {
        this['voiceConfig'] = voiceConfig;
    }
/**
     * @return {module:farsava_js_sdk/farsava_model/TTSAudioConfig}
     */
    getAudioConfig() {
        return this.audioConfig;
    }

    /**
     * @param {module:farsava_js_sdk/farsava_model/TTSAudioConfig} audioConfig
     */
    setAudioConfig(audioConfig) {
        this['audioConfig'] = audioConfig;
    }

}

/**
 * @member {module:farsava_js_sdk/farsava_model/SynthesisInput} synthesisInput
 */
TTSRequestBody.prototype['synthesisInput'] = undefined;

/**
 * @member {module:farsava_js_sdk/farsava_model/VoiceSelectionParams} voiceConfig
 */
TTSRequestBody.prototype['voiceConfig'] = undefined;

/**
 * @member {module:farsava_js_sdk/farsava_model/TTSAudioConfig} audioConfig
 */
TTSRequestBody.prototype['audioConfig'] = undefined;






export default TTSRequestBody;

