/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TTSVoiceGender.
* @enum {}
* @readonly
*/
export default class TTSVoiceGender {
    
        /**
         * value: "male"
         * @const
         */
        "male" = "male";

    
        /**
         * value: "female"
         * @const
         */
        "female" = "female";

    

    /**
    * Returns a <code>TTSVoiceGender</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:farsava_js_sdk/farsava_model/TTSVoiceGender} The enum <code>TTSVoiceGender</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

