/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ASRRequestBodyData from './farsava_model/ASRRequestBodyData';
import ASRRequestBodyURI from './farsava_model/ASRRequestBodyURI';
import ASRResponseBody from './farsava_model/ASRResponseBody';
import ASRStatus from './farsava_model/ASRStatus';
import AudioEncoding from './farsava_model/AudioEncoding';
import Error from './farsava_model/Error';
import HealthCheckResponseBody from './farsava_model/HealthCheckResponseBody';
import LMStatus from './farsava_model/LMStatus';
import LanguageCode from './farsava_model/LanguageCode';
import LanguageModelResult from './farsava_model/LanguageModelResult';
import LanguageModelTrainRequestBody from './farsava_model/LanguageModelTrainRequestBody';
import RecognitionAudioData from './farsava_model/RecognitionAudioData';
import RecognitionAudioURI from './farsava_model/RecognitionAudioURI';
import RecognitionConfig from './farsava_model/RecognitionConfig';
import SpeechRecognitionModel from './farsava_model/SpeechRecognitionModel';
import SpeechRecognitionResult from './farsava_model/SpeechRecognitionResult';
import SynthesisInput from './farsava_model/SynthesisInput';
import TTSAudioConfig from './farsava_model/TTSAudioConfig';
import TTSRequestBody from './farsava_model/TTSRequestBody';
import TTSResponseBody from './farsava_model/TTSResponseBody';
import TTSVoiceGender from './farsava_model/TTSVoiceGender';
import VoiceSelectionParams from './farsava_model/VoiceSelectionParams';
import WordInfo from './farsava_model/WordInfo';
import LanguageModelApi from './farsava_api/LanguageModelApi';
import SpeechApi from './farsava_api/SpeechApi';
import VoiceApi from './farsava_api/VoiceApi';


/**
* Farsava_API__Speech_Recognition_and_Text_to_Speech_by_applying_powerful_deep_neural_network_models_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FarsavaJsClient = require('farsava_js_sdk/index'); // See note below*.
* var xxxSvc = new FarsavaJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FarsavaJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['farsava_js_sdk/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FarsavaJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FarsavaJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module farsava_js_sdk/index
* @version 1.0.5
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:farsava_js_sdk/ApiClient}
     */
    ApiClient,

    /**
     * The ASRRequestBodyData model constructor.
     * @property {module:farsava_js_sdk/farsava_model/ASRRequestBodyData}
     */
    ASRRequestBodyData,

    /**
     * The ASRRequestBodyURI model constructor.
     * @property {module:farsava_js_sdk/farsava_model/ASRRequestBodyURI}
     */
    ASRRequestBodyURI,

    /**
     * The ASRResponseBody model constructor.
     * @property {module:farsava_js_sdk/farsava_model/ASRResponseBody}
     */
    ASRResponseBody,

    /**
     * The ASRStatus model constructor.
     * @property {module:farsava_js_sdk/farsava_model/ASRStatus}
     */
    ASRStatus,

    /**
     * The AudioEncoding model constructor.
     * @property {module:farsava_js_sdk/farsava_model/AudioEncoding}
     */
    AudioEncoding,

    /**
     * The Error model constructor.
     * @property {module:farsava_js_sdk/farsava_model/Error}
     */
    Error,

    /**
     * The HealthCheckResponseBody model constructor.
     * @property {module:farsava_js_sdk/farsava_model/HealthCheckResponseBody}
     */
    HealthCheckResponseBody,

    /**
     * The LMStatus model constructor.
     * @property {module:farsava_js_sdk/farsava_model/LMStatus}
     */
    LMStatus,

    /**
     * The LanguageCode model constructor.
     * @property {module:farsava_js_sdk/farsava_model/LanguageCode}
     */
    LanguageCode,

    /**
     * The LanguageModelResult model constructor.
     * @property {module:farsava_js_sdk/farsava_model/LanguageModelResult}
     */
    LanguageModelResult,

    /**
     * The LanguageModelTrainRequestBody model constructor.
     * @property {module:farsava_js_sdk/farsava_model/LanguageModelTrainRequestBody}
     */
    LanguageModelTrainRequestBody,

    /**
     * The RecognitionAudioData model constructor.
     * @property {module:farsava_js_sdk/farsava_model/RecognitionAudioData}
     */
    RecognitionAudioData,

    /**
     * The RecognitionAudioURI model constructor.
     * @property {module:farsava_js_sdk/farsava_model/RecognitionAudioURI}
     */
    RecognitionAudioURI,

    /**
     * The RecognitionConfig model constructor.
     * @property {module:farsava_js_sdk/farsava_model/RecognitionConfig}
     */
    RecognitionConfig,

    /**
     * The SpeechRecognitionModel model constructor.
     * @property {module:farsava_js_sdk/farsava_model/SpeechRecognitionModel}
     */
    SpeechRecognitionModel,

    /**
     * The SpeechRecognitionResult model constructor.
     * @property {module:farsava_js_sdk/farsava_model/SpeechRecognitionResult}
     */
    SpeechRecognitionResult,

    /**
     * The SynthesisInput model constructor.
     * @property {module:farsava_js_sdk/farsava_model/SynthesisInput}
     */
    SynthesisInput,

    /**
     * The TTSAudioConfig model constructor.
     * @property {module:farsava_js_sdk/farsava_model/TTSAudioConfig}
     */
    TTSAudioConfig,

    /**
     * The TTSRequestBody model constructor.
     * @property {module:farsava_js_sdk/farsava_model/TTSRequestBody}
     */
    TTSRequestBody,

    /**
     * The TTSResponseBody model constructor.
     * @property {module:farsava_js_sdk/farsava_model/TTSResponseBody}
     */
    TTSResponseBody,

    /**
     * The TTSVoiceGender model constructor.
     * @property {module:farsava_js_sdk/farsava_model/TTSVoiceGender}
     */
    TTSVoiceGender,

    /**
     * The VoiceSelectionParams model constructor.
     * @property {module:farsava_js_sdk/farsava_model/VoiceSelectionParams}
     */
    VoiceSelectionParams,

    /**
     * The WordInfo model constructor.
     * @property {module:farsava_js_sdk/farsava_model/WordInfo}
     */
    WordInfo,

    /**
    * The LanguageModelApi service constructor.
    * @property {module:farsava_js_sdk/farsava_api/LanguageModelApi}
    */
    LanguageModelApi,

    /**
    * The SpeechApi service constructor.
    * @property {module:farsava_js_sdk/farsava_api/SpeechApi}
    */
    SpeechApi,

    /**
    * The VoiceApi service constructor.
    * @property {module:farsava_js_sdk/farsava_api/VoiceApi}
    */
    VoiceApi
};
